[0m16:15:55.572574 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3AC7F34D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3AC7F0740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3AAE3A210>]}


============================== 16:15:55.598857 | 11769871-8f4a-4f45-9755-1d10a7012215 ==============================
[0m16:15:55.598857 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:15:55.599859 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\pt971\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init transform', 'send_anonymous_usage_stats': 'True'}
[0m16:15:55.681947 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/pt971/.dbt')}
[0m16:15:55.682912 [info ] [MainThread]: Creating dbt configuration folder at 
[0m16:15:55.685947 [debug] [MainThread]: Starter project path: C:\Users\pt971\code\db\.venv\Lib\site-packages\dbt\include\starter_project
[0m16:15:55.706030 [info ] [MainThread]: 
Your new dbt project "transform" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:15:55.707018 [info ] [MainThread]: Setting up your profile.
[0m16:16:09.275655 [info ] [MainThread]: Profile transform written to C:\Users\pt971\.dbt\profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m16:16:09.276659 [debug] [MainThread]: Command `dbt init` succeeded at 16:16:09.276659 after 13.85 seconds
[0m16:16:09.277656 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3AC6AF3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3ACAFED50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3A7B15040>]}
[0m16:16:09.277656 [debug] [MainThread]: Flushing usage events
[0m16:16:09.830217 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:36:37.271959 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002489ACB5850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002489C565DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002489C3AA930>]}


============================== 20:36:37.275501 | bce1ead9-5e7f-4425-8b9d-9594326a8cd2 ==============================
[0m20:36:37.275501 [info ] [MainThread]: Running with dbt=1.9.4
[0m20:36:37.276517 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\pt971\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt build', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:36:37.276517 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pt971\code\db\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:36:37.278533 [debug] [MainThread]: Command `dbt build` failed at 20:36:37.277539 after 0.19 seconds
[0m20:36:37.278533 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002489C565DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002489ABD1850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002489C7AD910>]}
[0m20:36:37.278533 [debug] [MainThread]: Flushing usage events
[0m20:36:37.769152 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:56:22.688250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C94E0D8B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C94529010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C910D1EE0>]}


============================== 20:56:22.693249 | 6704aa94-8d47-4e7c-a6de-2040c87c9925 ==============================
[0m20:56:22.693249 [info ] [MainThread]: Running with dbt=1.9.4
[0m20:56:22.694248 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\pt971\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt build -s ssb_data', 'send_anonymous_usage_stats': 'True'}
[0m20:56:22.694248 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pt971\code\db\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:56:22.695246 [debug] [MainThread]: Command `dbt build` failed at 20:56:22.695246 after 0.20 seconds
[0m20:56:22.695246 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C94D97770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C960A9EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C960A88C0>]}
[0m20:56:22.696248 [debug] [MainThread]: Flushing usage events
[0m20:56:23.249531 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:18:45.843463 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFD04C2FF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFCC85EF00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFD0E09070>]}


============================== 16:18:45.847601 | a2a81cd5-27a9-4dc3-9585-120f7e479840 ==============================
[0m16:18:45.847601 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:18:45.848729 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\pt971\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:18:45.848729 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pt971\code\db\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:18:45.849776 [debug] [MainThread]: Command `dbt run` failed at 16:18:45.849776 after 0.25 seconds
[0m16:18:45.849776 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFD04C3140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFD0FAC740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFD0FAC560>]}
[0m16:18:45.849776 [debug] [MainThread]: Flushing usage events
[0m16:18:46.351793 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:03:58.498480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2ED1EC440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2EE22BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2EE22B9D0>]}


============================== 21:03:58.507089 | bbf8f79a-688a-464a-9928-de5afd6aadd6 ==============================
[0m21:03:58.507089 [info ] [MainThread]: Running with dbt=1.10.13
[0m21:03:58.509084 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'use_colors': 'True', 'profiles_dir': 'C:\\Users\\pt971\\code\\db', 'log_format': 'default', 'cache_selected_only': 'False', 'warn_error': 'None', 'indirect_selection': 'eager', 'partial_parse': 'True', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True', 'log_path': 'logs', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'use_experimental_parser': 'False', 'version_check': 'True', 'quiet': 'False', 'introspect': 'True', 'empty': 'False', 'log_cache_events': 'False', 'debug': 'False', 'no_print': 'None', 'invocation_command': 'dbt build', 'printer_width': '80', 'write_json': 'True'}
[0m21:03:58.510364 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pt971\code\db\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:03:58.512979 [debug] [MainThread]: Command `dbt build` failed at 21:03:58.512714 after 0.27 seconds
[0m21:03:58.513682 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2EE0C3E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2EE126B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D2EE0BD9D0>]}
[0m21:03:58.514279 [debug] [MainThread]: Flushing usage events
[0m21:03:59.886620 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:19:45.908259 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9893FC440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E98A43BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E98A43B9D0>]}


============================== 21:19:45.915242 | df1db64f-3785-48bd-b5d1-0b37d8f6e3d3 ==============================
[0m21:19:45.915242 [info ] [MainThread]: Running with dbt=1.10.13
[0m21:19:45.916158 [debug] [MainThread]: running dbt with arguments {'log_format': 'default', 'printer_width': '80', 'no_print': 'None', 'invocation_command': 'dbt build', 'target_path': 'None', 'warn_error': 'None', 'indirect_selection': 'eager', 'fail_fast': 'False', 'log_path': 'logs', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'version_check': 'True', 'use_experimental_parser': 'False', 'quiet': 'False', 'introspect': 'True', 'empty': 'False', 'log_cache_events': 'False', 'debug': 'False', 'profiles_dir': 'C:\\Users\\pt971\\code\\db', 'use_colors': 'True', 'cache_selected_only': 'False', 'write_json': 'True'}
[0m21:19:45.916737 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pt971\code\db\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:19:45.917960 [debug] [MainThread]: Command `dbt build` failed at 21:19:45.917796 after 0.30 seconds
[0m21:19:45.918381 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E98A2D3E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E98A33AB10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E98A2CD9D0>]}
[0m21:19:45.918800 [debug] [MainThread]: Flushing usage events
[0m21:19:46.926017 [debug] [MainThread]: An error was encountered while trying to flush usage events
